/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M8
 * Generated at: 2016-07-29 14:24:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Random;

public final class BookNow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

String uid,tid;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Random");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"utf-8\">\n");
      out.write("\t    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t    <title>Book your seat now!!</title>\n");
      out.write("\t    <link href=\"bootstrap-3.3.6-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link href=\"bootstrap-3.3.6-dist/css/bootstrap-theme.min.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link href=\"font-awesome-4.6.3/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link href=\"bootstrap-social-gh-pages/bootstrap-social.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link href=\"css/booking.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link rel=\"icon\" type=\"png\" href=\"img/tour.ico\">\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t   ");

			   	  if(request.getAttribute("ERRORMSG") != null)
			   	  {
			   		  out.print("<font color = red size=3>");
			       	  out.print(request.getAttribute("ERRORMSG"));
			       	  out.print("</font>");
			       	  out.print("<br>");
			      }
			   
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\t\t");

			uid=(String)session.getAttribute("uid");
			tid=request.getParameter("tid"); 
			Random r = new Random();
			int x=r.nextInt(60000);
			String bid="B"+x;
		
		
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<h2 style=\"text-align: center\">Booking Form</h2>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" action=\"BookNowServlet\" role =\"form\" method=\"post\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"bid\">BookingId</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"bookingid\" id=\"bid\" class=\"form-control\"  value=\"");
      out.print(bid);
      out.write("\" readonly=\"readonly\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"tid\">TourId</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"tourid\" id=\"tid\" class=\"form-control\"  value=\"");
      out.print(tid);
      out.write("\" readonly=\"readonly\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"uid\">Email</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-3\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"uid\" class=\"form-control\" value=\"");
      out.print(uid);
      out.write("\" readonly=\"readonly\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"frstper\">First person name</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-3\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name1\" id=\"frstper\" class=\"form-control\" placeholder=\"Enter name here!\" required>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"frstage\">Age</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"age1\" id=\"frstage\" class=\"form-control\" placeholder=\"Enter age\" required>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"frstgender\">Gender</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" value=\"Male\" name=\"gender1\">Male</label>\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" value=\"Female\" name=\"gender1\">Female</label>\n");
      out.write("\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"secper\">Second person name</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-3\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"name2\" id=\"secper\" class=\"form-control\" placeholder=\"Enter name here!\" required>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"secage\">Age</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"age2\" id=\"secage\" class=\"form-control\" placeholder=\"Enter age\" required>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"secgender\">Gender</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" value=\"Male\" name=\"gender2\">Male</label>\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" value=\"Female\" name=\"gender2\">Female</label>\n");
      out.write("\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t  <label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"room1\">Room Type you will prefer</label>\n");
      out.write("\t\t\t\t\t  <div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t   <select class=\"form-control\" name=\"room\" id=\"room11\">\n");
      out.write("\t\t\t\t\t\t    <option>AC</option>\n");
      out.write("\t\t\t\t\t\t    <option>NonAC</option>\n");
      out.write("\t\t\t\t\t   </select>\n");
      out.write("\t\t\t\t\t   </div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t  <label class=\"control-label col-sm-2 col-sm-offset-2\" for=\"foo1\">Food type</label>\n");
      out.write("\t\t\t\t\t  <div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t   <select class=\"form-control\" name=\"food\" id=\"foo1\">\n");
      out.write("\t\t\t\t\t\t    <option>Vegetarian</option>\n");
      out.write("\t\t\t\t\t\t    <option>Non Vegetarian</option>\n");
      out.write("\t\t\t\t\t   </select>\n");
      out.write("\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success btn-md col-sm-offset-6\" value=\"Book\">\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" class=\"btn btn-warning btn-sm col-sm-offset-2\" value=\"Reset Details\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
