/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M8
 * Generated at: 2016-07-26 07:26:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en-US\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <title>Tourister</title>\n");
      out.write("      \t<link href=\"bootstrap-3.3.6-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link href=\"bootstrap-3.3.6-dist/css/bootstrap-theme.min.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link href=\"font-awesome-4.6.3/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link href=\"bootstrap-social-gh-pages/bootstrap-social.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("\t    <link rel=\"icon\" type=\"png\" href=\"img/tour.ico\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("    <body>\n");
      out.write("    \t<div>\n");
      out.write("               ");

                  if(request.getAttribute("MSG") != null)
                  {
                      out.print("<font color = green size=3>");
                      out.print(request.getAttribute("MSG"));
                      out.print("</font>");
                      out.print("<br>");
                  }
               
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div>\n");
      out.write("               ");

                  if(request.getAttribute("ERRORMSG") != null)
                  {
                      out.print("<font color = red size=3>");
                      out.print(request.getAttribute("ERRORMSG"));
                      out.print("</font>");
                      out.print("<br>");
                  }
               
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div>\n");
      out.write("               ");

                  if(request.getAttribute("ERRORMSG5") != null)
                  {
                      out.print("<font color = red size=3>");
                      out.print(request.getAttribute("ERRORMSG5"));
                      out.print("</font>");
                      out.print("<br>");
                  }
               
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div>\n");
      out.write("            ");

                if(request.getAttribute("ERRORMSG1") != null)
                {
                        out.println("<font color = red size=3>");
                        out.println(request.getAttribute("ERRORMSG1"));
                        out.println("</font>");
                        out.println("<br>");
                }
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- START OF NAVIGATION BAR -->\n");
      out.write("        <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                    </button>\n");
      out.write("                   </div>\n");
      out.write("                    <div id=\"navbar\" class=\"navbar-collapse collapse\">\n");
      out.write("                        <ul class=\"nav navbar-nav\">\n");
      out.write("                            <li class=\"active\">\n");
      out.write("                                <a href=\"#\"><span class=\"glyphicon glyphicon-home\" aria-hidden=\"true\"></span> Home</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"about.html\"><span class=\"glyphicon glyphicon-info-sign\" aria-hidden=\"true\"></span> About</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"contact.html\"><i class=\"fa fa-envelope-o\"></i> Contact</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                        <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                            <li><a href=\"CustomerRegistration.jsp\"><span class=\"glyphicon glyphicon-user\"></span>Sign up</a></li>\n");
      out.write("                            <li><a id=\"loginbtn\"><span class=\"glyphicon glyphicon-log-in\"></span> User</a></li>\n");
      out.write("                            <li><a id=\"loginbtn1\"><span class=\"glyphicon glyphicon-log-in\"></span> Admin</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                 </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!-- Modal for user login -->\n");
      out.write("        <div id=\"loginModal\" class=\"modal fade\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <!--Modal content-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                        <h4 class=\"modal-title\">Login</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body modal-lg\">\n");
      out.write("                        <!--Form from Here-->\n");
      out.write("                         <form class=\"form-inline\" role=\"login\" action=\"CustomerLoginServlet\" method=\"post\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"sr-only\" for=\"inputemail\">Email</label>\n");
      out.write("                                <input type=\"email\" class=\"form-control input-sm\" placeholder=\"Email\" name=\"email\" id=\"inputemail\">\n");
      out.write("                                <label class=\"sr-only\" for=\"pwd\">Password</label>\n");
      out.write("                                <input type=\"password\" class=\"form-control input-sm\" placeholder=\"Password\" name=\"password\" id=\"pwd\">\n");
      out.write("                                <div class=\"checkbox\">\n");
      out.write("                                    <label>\n");
      out.write("                                        <input type=\"checkbox\">Remember me\n");
      out.write("                                     </label>\n");
      out.write("                                 </div>\n");
      out.write("                            </div><!-- END OF DIV FORM-GROUP -->\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-info btn-sm\">Sign in</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-default btn-sm\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("                        </form>\n");
      out.write("                    </div> <!-- END OF MODAL BODY -->      \n");
      out.write("                </div><!-- END OF MODAL CONTENT -->\n");
      out.write("            </div><!-- END OF MODAL-DIALOG -->\n");
      out.write("        </div><!-- END OF LOGIN MODAL -->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("         <!-- Modal for admin login -->\n");
      out.write("        <div id=\"loginModal1\" class=\"modal fade\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <!--Modal content-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                        <h4 class=\"modal-title\">Login</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body modal-lg\">\n");
      out.write("                        <!--Form from Here-->\n");
      out.write("                         <form class=\"form-inline\" role=\"login\" action=\"AdminLoginServlet\" method=\"post\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"sr-only\" for=\"inputemail\">Email</label>\n");
      out.write("                                <input type=\"email\" class=\"form-control input-sm\" placeholder=\"Email\" name=\"email\" id=\"inputemail\">\n");
      out.write("                                <label class=\"sr-only\" for=\"inputpwd\">Password</label>\n");
      out.write("                                <input type=\"password\" class=\"form-control input-sm\" placeholder=\"Password\" name=\"password\" id=\"inputpwd\">\n");
      out.write("                                <div class=\"checkbox\">\n");
      out.write("                                    <label>\n");
      out.write("                                        <input type=\"checkbox\">Remember me\n");
      out.write("                                     </label>\n");
      out.write("                                 </div>\n");
      out.write("                            </div><!-- END OF DIV FORM-GROUP -->\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-info btn-sm\">Sign in</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-default btn-sm\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("                        </form>\n");
      out.write("                    </div> <!-- END OF MODAL BODY -->      \n");
      out.write("                </div><!-- END OF MODAL CONTENT -->\n");
      out.write("            </div><!-- END OF MODAL-DIALOG -->\n");
      out.write("        </div><!-- END OF LOGIN MODAL -->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("\n");
      out.write("        <header class=\"jumbotron\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row row-header\">\n");
      out.write("                    <div class=\"col-xs-12 col-sm-8\">\n");
      out.write("                        <h1>Tourister</h1>\n");
      out.write("                        <p style=\"padding:40px\"></p>\n");
      out.write("                        <p>We take inspiration from the World's best \n");
      out.write("                            touring experiences, and create a unique experience. You will surely be surprised by our amazing offers and deals we\n");
      out.write("                            provide throughout the year !\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("    </header>\n");
      out.write("       <!-- <div class=\"container\">-->\n");
      out.write("        \t\n");
      out.write("       \t\t <div class=\"row row-content\">\n");
      out.write("            \t\n");
      out.write("                <div class=\"col-xs-12\">\n");
      out.write("                    <div id=\"mycarousel\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("                        <!--Indicators-->\n");
      out.write("                        <ol class=\"carousel-indicators\">\n");
      out.write("                            <li data-target=\"#mycarousel\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                            <li data-target=\"#mycarousel\" data-slide-to=\"1\"></li>\n");
      out.write("                            <li data-target=\"#mycarousel\" data-slide-to=\"2\"></li>\n");
      out.write("                            <li data-target=\"#mycarousel\" data-slide-to=\"3\"></li>\n");
      out.write("                            <li data-target=\"#mycarousel\" data-slide-to=\"4\"></li>\n");
      out.write("                        </ol>\n");
      out.write("                        <!--Wrapper for slide-->    \n");
      out.write("                        <div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("                            <div class=\"item active\">\n");
      out.write("                                <img class=\"img-responsive\" src=\"img/image1.jpg\" alt=\"Manali\">\n");
      out.write("                                <div class=\"carousel-caption\">\n");
      out.write("                                      <h3>Manali <span class=\"label label-danger label-sm\">New</span></h3>\n");
      out.write("                                      <p>The atmosphere in Manali has a touch of Florence and Venice.\n");
      out.write("                                      \t\tExclusive deals only at Rs.12000 per head</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"item\">\n");
      out.write("                                <img class=\"img-responsive\" src=\"img/image2.jpg\" alt=\"Anjuna Beach Goa\">\n");
      out.write("                                <div class=\"carousel-caption\">\n");
      out.write("                                      <h3>Anjuna Beach<span class=\"label label-danger label-sm\">Just arrived</span></h3>\n");
      out.write("                                      <p>One of the most visited places in India\n");
      out.write("                                      \t\tDeals starting only at Rs.6000 per head\n");
      out.write("                                      \t</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"item\">\n");
      out.write("                                <img class=\"img-responsive\" src=\"img/image3.jpg\" alt=\"Forest\">\n");
      out.write("                                <div class=\"carousel-caption\">\n");
      out.write("                                      <h3>Sundarban<span class=\"label label-danger label-sm\">New</span></h3>\n");
      out.write("                                      <p>Talk about forest adventures and nothing can beat Sundarban<br>\n");
      out.write("                                      \t\tDeals starting only at Rs.10000 per person\n");
      out.write("                                      </p>\n");
      out.write("                                 </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"item\">\n");
      out.write("                                <img class=\"img-responsive\" src=\"img/image4.jpg\" alt=\"Greenery\">\n");
      out.write("                                <div class=\"carousel-caption\">\n");
      out.write("                                      <h3>Darjeeling<span class=\"label label-danger label-sm\">New</span></h3>\n");
      out.write("                                      <p style=\"color: white;\">The most beautiful hill station in India \n");
      out.write("                                      \t\tWinter Deals starting only at Rs.11000 per head\n");
      out.write("                                      </p>\n");
      out.write("                                 </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"item\">\n");
      out.write("                                <img class=\"img-responsive\" src=\"img/image5.jpg\" style=\"background-size: 100% 100%;\" alt=\"Religious\">\n");
      out.write("                                 <div class=\"carousel-caption\">\n");
      out.write("                                      <h3>The Golden Temple<span class=\"label label-danger label-sm\">New</span></h3>\n");
      out.write("                                      <p style=\"color: white;\">Where the heart meats soul.Get ready for an amazing tour to the land of Punjabis<br>\n");
      out.write("                                      \t\tDeals starting only at Rs.10000 per head\n");
      out.write("                                      </p>\n");
      out.write("                                 </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Left and right controls -->\n");
      out.write("                            <a class=\"left carousel-control\" href=\"#mycarousel\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                              <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\n");
      out.write("                              <span class=\"sr-only\">Previous</span>\n");
      out.write("                            </a>\n");
      out.write("                            <a class=\"right carousel-control\" href=\"#mycarousel\" role=\"button\" data-slide=\"next\">\n");
      out.write("                              <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\n");
      out.write("                              <span class=\"sr-only\">Next</span>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("        <footer class=\"row-footer\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">             \n");
      out.write("                <div class=\"col-xs-5 col-xs-offset-1 col-sm-2 col-sm-offset-1\">\n");
      out.write("                    <h5>Links</h5>\n");
      out.write("                    <ul class=\"list-unstyled\">\n");
      out.write("                        <li><a href=\"#\">Home</a></li>\n");
      out.write("                        <li><a href=\"about.html\">AboutUs</a></li>\n");
      out.write("                        <li><a href=\"contact.html\">Contact</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xs-6 col-sm-5\">\n");
      out.write("                    <h5>Our Address</h5>\n");
      out.write("                    <address style=\"font-size: 100%\">\n");
      out.write("                       243/P, Maniktala main road,<br>\n");
      out.write("                       Kolkata-54<br>\n");
      out.write("                      <i class=\"fa fa-phone\"></i>: +91 9804567875<br>\n");
      out.write("                      <i class=\"fa fa-fax\"></i>: +91 9321891022<br>\n");
      out.write("                      <i class=\"fa fa-envelope\"></i>: \n");
      out.write("                        <a href=\"mailto:tourister@gmail.com\">tourister@gmail.com</a>\n");
      out.write("                   </address>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xs-12 col-sm-4\">\n");
      out.write("                    <div class=\"nav navbar-nav\" style=\"padding: 40px 10px;\">\n");
      out.write("                        <a class=\"btn btn-social-icon btn-google-plus\" href=\"http://google.com/+\"><i class=\"fa fa-google-plus\"></i></a>\n");
      out.write("                        <a class=\"btn btn-social-icon btn-facebook\" href=\"http://www.facebook.com/profile.php?id=\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a class=\"btn btn-social-icon btn-linkedin\" href=\"http://www.linkedin.com/in/\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("                        <a class=\"btn btn-social-icon btn-twitter\" href=\"http://twitter.com/\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a class=\"btn btn-social-icon btn-youtube\" href=\"http://youtube.com/\"><i class=\"fa fa-youtube\"></i></a>\n");
      out.write("                        <a class=\"btn btn-social-icon\" href=\"mailto:\"><i class=\"fa fa-envelope-o\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-sm-12\">\n");
      out.write("                        <p style=\"padding:10px;\"></p>\n");
      out.write("                        <p align=center>&copy; Copyright 2016 Tourister</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>  \n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("     <script src=\"jquery/dist/jquery.min.js\"></script>\n");
      out.write("        <script src=\"bootstrap-3.3.6-dist/js/bootstrap.min.js\"></script>\n");
      out.write("        <!--Adding the javascript code for carousel-->\n");
      out.write("        <script>\n");
      out.write("            $(document).ready(function(){\n");
      out.write("                     $(\"#loginbtn\").click(function(){\n");
      out.write("                        $(\"#loginModal\").modal(\"show\");\n");
      out.write("                        });\n");
      out.write("                      $(\"#loginbtn1\").click(function(){\n");
      out.write("                          $(\"#loginModal1\").modal(\"show\");\n");
      out.write("                          });\n");
      out.write("                    });\n");
      out.write("        </script>\n");
      out.write("      </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
